plugins {
    id 'com.android.application'
}

android {
    namespace 'com.remote3.tivimateobserver'
    compileSdk 33
    buildToolsVersion '33.0.2'

    defaultConfig {
        applicationId 'com.remote3.tivimateobserver'
        minSdk 26
        targetSdk 33
        versionCode 1
        versionName '1.0.0'
    }

    signingConfigs {
        release {
            def keystorePath = System.getenv('OBSERVER_KEYSTORE_PATH')
            if (keystorePath) {
                storeFile file(keystorePath)
                storePassword System.getenv('OBSERVER_KEYSTORE_PASSWORD')
                keyAlias System.getenv('OBSERVER_KEY_ALIAS')
                keyPassword System.getenv('OBSERVER_KEY_PASSWORD')
            }
        }
    }

    buildTypes {
        release {
            minifyEnabled false
            signingConfig signingConfigs.release
        }
    }
}
